// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUij1AoCnXEvBqu1v19fLYTO73KOGWmgA',
    appId: '1:76179772213:web:a0c607d3de1f9488c1f27c',
    messagingSenderId: '76179772213',
    projectId: 'fyppharma-2a671',
    authDomain: 'fyppharma-2a671.firebaseapp.com',
    databaseURL: 'https://fyppharma-2a671-default-rtdb.firebaseio.com',
    storageBucket: 'fyppharma-2a671.appspot.com',
    measurementId: 'G-GLFC5E0V9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4vVsWct3HvEq2IA5rcXy-zzLTPOKi0zA',
    appId: '1:76179772213:android:b0bd88646aee8b0dc1f27c',
    messagingSenderId: '76179772213',
    projectId: 'fyppharma-2a671',
    databaseURL: 'https://fyppharma-2a671-default-rtdb.firebaseio.com',
    storageBucket: 'fyppharma-2a671.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRaTP65vWzxBonYiMDQddZKTsoFxqRyro',
    appId: '1:76179772213:ios:bf840508f12b784cc1f27c',
    messagingSenderId: '76179772213',
    projectId: 'fyppharma-2a671',
    databaseURL: 'https://fyppharma-2a671-default-rtdb.firebaseio.com',
    storageBucket: 'fyppharma-2a671.appspot.com',
    iosBundleId: 'com.example.fitnessSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRaTP65vWzxBonYiMDQddZKTsoFxqRyro',
    appId: '1:76179772213:ios:4010200ea73bd36bc1f27c',
    messagingSenderId: '76179772213',
    projectId: 'fyppharma-2a671',
    databaseURL: 'https://fyppharma-2a671-default-rtdb.firebaseio.com',
    storageBucket: 'fyppharma-2a671.appspot.com',
    iosBundleId: 'com.example.fitnessSocial.RunnerTests',
  );
}
